# Generated by Django 4.1.2 on 2022-10-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['name']},
        ),
    ]
